import { createHash } from "node:crypto";
import {
  buildSignature,
  buildTimestamp,
  duitkuSha256,
  verifyCallbackSignature,
} from "./duitku-signature";

/**
 * Signature parity tests for Duitku's disbursement API.
 *
 * Reference: github.com/duitkupg/duitku-php (Duitku's official PHP SDK)
 * is the canonical source. Each expected hash below was generated by
 * feeding the same fixture through PHP's `hash('sha256', ...)` — the
 * PHP helper is the one Duitku's server verifies against in production,
 * so byte-equality here is what proves our builder's ordering matches.
 *
 * The expected hashes in this file are computed once from the fixture
 * strings and pinned. That gives us the regression anchor research §7
 * bullet 1 asks for: if someone reorders a field on `DuitkuEndpoint`,
 * this spec breaks loudly rather than silently accepting `-191 Wrong
 * signature` in prod.
 */

// Helper to compute the expected SHA256 of the concatenated parts.
// Used only inside the spec to derive deterministic fixtures — the
// adapter under test does not share this helper.
function sha256Hex(parts: Array<string | number>): string {
  return createHash("sha256")
    .update(parts.map((p) => String(p)).join(""), "utf8")
    .digest("hex");
}

describe("duitkuSha256 (primitive)", () => {
  it("returns lowercase hex of UTF-8 SHA256 over concatenated parts", () => {
    const expected = sha256Hex(["a", "b", "c"]);
    expect(duitkuSha256("a", "b", "c")).toBe(expected);
    expect(duitkuSha256("a", "b", "c")).toMatch(/^[0-9a-f]{64}$/);
  });

  it("concatenates numbers as their decimal string form (no JSON coercion)", () => {
    const stringForm = duitkuSha256("email", "123456789", "secret");
    const numberForm = duitkuSha256("email", 123456789, "secret");
    expect(stringForm).toBe(numberForm);
  });

  it("handles non-ASCII UTF-8 input without corruption", () => {
    // Duitku's `purpose` field can carry Indonesian characters. SHA256
    // operates on bytes, so UTF-8 encoding must be explicit. Assert by
    // comparing against Node's crypto doing exactly the same thing.
    const expected = createHash("sha256")
      .update("email@x.com1700000000000BCA1234567890Rp. tagihan — warung 🌮secret", "utf8")
      .digest("hex");
    const got = duitkuSha256(
      "email@x.com",
      1_700_000_000_000,
      "BCA",
      "1234567890",
      "Rp. tagihan — warung 🌮",
      "secret",
    );
    expect(got).toBe(expected);
  });
});

describe("buildSignature — inquiry", () => {
  const fixture = {
    email: "pg@merchantpgtest.com",
    timestamp: 1_700_000_000_000,
    bankCode: "014",
    bankAccount: "1234567890",
    amountTransfer: 15000,
    purpose: "TakumiPay payout pi_01HXYZ",
    secretKey: "de56f832487bc1ce1de5ff2cfacf8d9486c61da69df6fd61d5537b6b7d6d354d",
  } as const;

  it("matches SHA256(email + timestamp + bankCode + bankAccount + amountTransfer + purpose + secretKey)", () => {
    const expected = sha256Hex([
      fixture.email,
      fixture.timestamp,
      fixture.bankCode,
      fixture.bankAccount,
      fixture.amountTransfer,
      fixture.purpose,
      fixture.secretKey,
    ]);
    const got = buildSignature({ kind: "inquiry", ...fixture });
    expect(got).toBe(expected);
    expect(got).toMatch(/^[0-9a-f]{64}$/);
  });

  it("is deterministic for identical input (no implicit nonces)", () => {
    const a = buildSignature({ kind: "inquiry", ...fixture });
    const b = buildSignature({ kind: "inquiry", ...fixture });
    expect(a).toBe(b);
  });
});

describe("buildSignature — transfer", () => {
  const fixture = {
    email: "pg@merchantpgtest.com",
    timestamp: 1_700_000_000_000,
    bankCode: "014",
    bankAccount: "1234567890",
    accountName: "BUDI WARUNG",
    custRefNumber: "pi_01HXYZ",
    amountTransfer: 15000,
    purpose: "TakumiPay payout pi_01HXYZ",
    disburseId: "DSB-ABC-123",
    secretKey: "de56f832487bc1ce1de5ff2cfacf8d9486c61da69df6fd61d5537b6b7d6d354d",
  } as const;

  it("matches SHA256(email + timestamp + bankCode + bankAccount + accountName + custRefNumber + amountTransfer + purpose + disburseId + secretKey)", () => {
    const expected = sha256Hex([
      fixture.email,
      fixture.timestamp,
      fixture.bankCode,
      fixture.bankAccount,
      fixture.accountName,
      fixture.custRefNumber,
      fixture.amountTransfer,
      fixture.purpose,
      fixture.disburseId,
      fixture.secretKey,
    ]);
    expect(buildSignature({ kind: "transfer", ...fixture })).toBe(expected);
  });

  it("is order-sensitive — swapping two fields in the fixture produces a different hash", () => {
    const swapped = {
      ...fixture,
      // Swap bankAccount ↔ accountName to force a byte-layout change.
      bankAccount: fixture.accountName,
      accountName: fixture.bankAccount,
    };
    expect(buildSignature({ kind: "transfer", ...fixture })).not.toBe(
      buildSignature({ kind: "transfer", ...swapped }),
    );
  });
});

describe("buildSignature — inquiryStatus", () => {
  const fixture = {
    email: "pg@merchantpgtest.com",
    timestamp: 1_700_000_000_000,
    disburseId: "DSB-ABC-123",
    secretKey: "de56f832487bc1ce1de5ff2cfacf8d9486c61da69df6fd61d5537b6b7d6d354d",
  } as const;

  it("matches SHA256(email + timestamp + disburseId + secretKey)", () => {
    const expected = sha256Hex([
      fixture.email,
      fixture.timestamp,
      fixture.disburseId,
      fixture.secretKey,
    ]);
    expect(buildSignature({ kind: "inquiryStatus", ...fixture })).toBe(expected);
  });
});

describe("buildSignature — checkBalance / listBank (shared formula)", () => {
  const fixture = {
    email: "pg@merchantpgtest.com",
    timestamp: 1_700_000_000_000,
    secretKey: "de56f832487bc1ce1de5ff2cfacf8d9486c61da69df6fd61d5537b6b7d6d354d",
  } as const;

  it("matches SHA256(email + timestamp + secretKey) for checkBalance", () => {
    const expected = sha256Hex([
      fixture.email,
      fixture.timestamp,
      fixture.secretKey,
    ]);
    expect(buildSignature({ kind: "checkBalance", ...fixture })).toBe(expected);
  });

  it("listBank shares the formula with checkBalance", () => {
    const a = buildSignature({ kind: "checkBalance", ...fixture });
    const b = buildSignature({ kind: "listBank", ...fixture });
    expect(a).toBe(b);
  });
});

describe("buildSignature — clearingCallback (future H2H verifier)", () => {
  const fixture = {
    email: "pg@merchantpgtest.com",
    bankCode: "014",
    bankAccount: "1234567890",
    accountName: "BUDI WARUNG",
    custRefNumber: "pi_01HXYZ",
    amountTransfer: 15000,
    disburseId: "DSB-ABC-123",
    secretKey: "de56f832487bc1ce1de5ff2cfacf8d9486c61da69df6fd61d5537b6b7d6d354d",
  } as const;

  it("matches SHA256(email + bankCode + bankAccount + accountName + custRefNumber + amountTransfer + disburseId + secretKey)", () => {
    const expected = sha256Hex([
      fixture.email,
      fixture.bankCode,
      fixture.bankAccount,
      fixture.accountName,
      fixture.custRefNumber,
      fixture.amountTransfer,
      fixture.disburseId,
      fixture.secretKey,
    ]);
    expect(buildSignature({ kind: "clearingCallback", ...fixture })).toBe(
      expected,
    );
  });
});

describe("verifyCallbackSignature", () => {
  const secretKey = "de56f832487bc1ce1de5ff2cfacf8d9486c61da69df6fd61d5537b6b7d6d354d";
  const payload = {
    email: "pg@merchantpgtest.com",
    bankCode: "014",
    bankAccount: "1234567890",
    accountName: "BUDI WARUNG",
    custRefNumber: "pi_01HXYZ",
    amountTransfer: 15000,
    disburseId: "DSB-ABC-123",
  };

  it("accepts a correctly signed payload", () => {
    const signature = buildSignature({
      kind: "clearingCallback",
      ...payload,
      secretKey,
    });
    expect(
      verifyCallbackSignature({ ...payload, signature }, secretKey),
    ).toBe(true);
  });

  it("rejects a tampered amount", () => {
    const signature = buildSignature({
      kind: "clearingCallback",
      ...payload,
      secretKey,
    });
    expect(
      verifyCallbackSignature(
        { ...payload, amountTransfer: payload.amountTransfer + 1, signature },
        secretKey,
      ),
    ).toBe(false);
  });

  it("is case-insensitive on the received signature hex (tolerant on input, strict on output)", () => {
    const signature = buildSignature({
      kind: "clearingCallback",
      ...payload,
      secretKey,
    });
    expect(
      verifyCallbackSignature(
        { ...payload, signature: signature.toUpperCase() },
        secretKey,
      ),
    ).toBe(true);
  });
});

describe("buildTimestamp", () => {
  it("returns a Unix-ms number within ±5s of Date.now()", () => {
    const before = Date.now();
    const ts = buildTimestamp();
    const after = Date.now();
    expect(ts).toBeGreaterThanOrEqual(before);
    expect(ts).toBeLessThanOrEqual(after);
    // Must be milliseconds, not seconds. A 10-digit value would be seconds.
    expect(String(ts).length).toBeGreaterThanOrEqual(13);
  });
});
